# Allowed values are low-end / mid-end / high-end
Acura: 'mid-end'
Alfa Romeo: 'mid-end'
Audi: 'high-end'
BMW: 'high-end'
Buick: 'mid-end'
Cadillac: 'high-end'
Chery: 'low-end'
Chevrolet: 'mid-end'
Chrysler: 'mid-end'
Citroen: 'mid-end'
Dacia: 'low-end'
Daewoo: 'low-end'
Dodge: 'high-end'
Fiat: 'mid-end'
Ford: 'mid-end'
Geely: 'low-end'
Great Wall: 'low-end'
Honda: 'mid-end'
Hyundai: 'mid-end'
Infiniti: 'high-end'
Iveco: 'low-end'
Jaguar: 'high-end'
Jeep: 'mid-end'
Kia: 'mid-end'
LADA: 'low-end'
Lancia: 'mid-end'
Land Rover: 'high-end'
Lexus: 'high-end'
Lifan: 'low-end'
Lincoln: 'high-end'
Mazda: 'mid-end'
Mercedes-Benz: 'high-end'
Mini: 'mid-end'
Mitsubishi: 'mid-end'
Nissan: 'mid-end'
Opel: 'mid-end'
Peugeot: 'low-end'
Pontiac: 'mid-end'
Porsche: 'high-end'
Renault: 'mid-end'
Rover: 'low-end'
Saab: 'mid-end'
Seat: 'mid-end'
Skoda: 'mid-end'
SsangYong: 'low-end'
Subaru: 'mid-end'
Suzuki: 'mid-end'
Toyota: 'mid-end'
Volkswagen: 'mid-end'
Volvo: 'mid-end'
ВАЗ: 'low-end'
ГАЗ: 'low-end'
ЗАЗ: 'low-end'
Москвич: 'low-end'
УАЗ: 'low-end'
