Acura: 'Japan'
Alfa Romeo: 'Italy'
Audi: 'Germany'
BMW: 'Germany'
Buick: 'United States'
Cadillac: 'United States'
Chery: 'China'
Chevrolet: 'United States'
Chrysler: 'United States'
Citroen: 'France'
Dacia: 'Romania'
Daewoo: 'South Korea'
Dodge: 'United States'
Fiat: 'Italy'
Ford: 'United States'
Geely: 'China'
Great Wall: 'China'
Honda: 'Japan'
Hyundai: 'South Korea'
Infiniti: 'Japan'
Iveco: 'Italy'
Jaguar: 'United Kingdom'
Jeep: 'United States'
Kia: 'South Korea'
LADA: 'Russia'
Lancia: 'Italy'
Land Rover: 'United Kingdom'
Lexus: 'Japan'
Lifan: 'China'
Lincoln: 'United States'
Mazda: 'Japan'
Mercedes-Benz: 'Germany'
Mitsubishi: 'Japan'
Mini: 'United Kingdom'
Nissan: 'Japan'
Opel: 'Germany'
Peugeot: 'France'
Pontiac: 'United States'
Porsche: 'Germany'
Renault: 'France'
Rover: 'United Kingdom'
Saab: 'Sweden'
Seat: 'Spain'
Skoda: 'Czech Republic'
SsangYong: 'South Korea'
Subaru: 'Japan'
Suzuki: 'Japan'
Toyota: 'Japan'
Volkswagen: 'Germany'
Volvo: 'Sweden'
ВАЗ: 'Russia'
ГАЗ: 'Russia'
ЗАЗ: 'Russia'
Москвич: 'Russia'
УАЗ: 'Russia'
